name: Intégration continue

on:
 push:
   branches:
     - main

permissions:
   contents: read
   packages: write

jobs:
 test:
   runs-on: self-hosted
   steps:
     - name: Récupérer le code
       uses: actions/checkout@v4

     - name: Vérifier les fichiers du projet
       run: ls -la

     - name: Construire l'image Docker
       run: docker build -t devops-app .

     - name: Se connecter à GHCR
       run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

     - name: Taguer l'image pour GHCR
       run: docker tag devops-app ghcr.io/melinda08/devops-projet:latest

     - name: Envoyer l'image vers GHCR
       run: docker push ghcr.io/melinda08/devops-projet:latest

     - name: Nettoyer l'ancien conteneur
       run: docker rm -f devops-app-test || true

     - name: Démarrer le conteneur
       run: docker run -d --name devops-app-test -p 8081:8080 devops-app

     - name: Vérifier que le conteneur tourne
       run: docker ps -a

     - name: Voir les logs du conteneur
       run: docker logs devops-app-test

     - name: Attendre le démarrage de l'application
       run: sleep 3

     - name: Tester l'application
       run: curl http://localhost:8081

     - name: Vérifier la réponse
       run: |
         reponse=$(curl -s http://localhost:8081)
         test "$reponse" = "Bonjour depuis mon application DevOps !"

     - name: Récupérer la nouvelle image depuis GHCR
       run: docker pull ghcr.io/melinda08/devops-projet:latest

     - name: Arrêter l'ancien conteneur de production
       run: docker rm -f devops-prod || true

     - name: Démarrer la nouvelle version en production
       run: docker run -d --name devops-prod -p 8082:8080 ghcr.io/melinda08/devops-projet:latest

     - name: Attendre le démarrage de la production
       run: sleep 3

     - name: Tester la production
       run: curl http://localhost:8082

     - name: Vérifier la réponse de production
       run: |
         reponse=$(curl -s http://localhost:8082)
         test "$reponse" = "Bonjour depuis mon application DevOps !"
