name: Intégration continue

on:
 push:
   branches:
     - main

permissions:
   contents: read
   packages: write

jobs:
 test:
   runs-on: self-hosted
   steps:
     - name: Récupérer le code
       uses: actions/checkout@v4

     - name: Vérifier les fichiers du projet
       run: ls -la

     - name: Construire l'image Docker
       run: docker build -t devops-app .

     - name: Démarrer le conteneur
       run: docker run -d --name devops-app-test -p 8081:8080 devops-app

     - name: Vérifier que le conteneur tourne
       run: docker ps -a

     - name: Voir les logs du conteneur
       run: docker logs devops-app-test

     - name: Attendre le démarrage de l'application
       run: sleep 3

     - name: Tester l'application
       run: curl http://localhost:8081

     - name: Vérifier la réponse
       run: |
         reponse=$(curl -s http://localhost:8081)
         test "$reponse" = "Bonjour depuis mon application DevOps !"

